name: Proxmox Schema Dump [WIP]

on:
  workflow_dispatch:

#permissions:
#  contents: write
env:
  DISTRO: bullseye
  PROXMOX_VERSION: 7.0-2

jobs:
  dump_schema:
    name: Dump API Schema
    runs-on: ubuntu-latest
    outputs:
      distro: ${{ steps.prepare.outputs.distro }}
      proxmox_version: ${{ steps.prepare.outputs.proxmox_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          
      - name: Prepare
        id: prepare
        run: |
          echo "distro=${{ env.DISTRO }}" >> "$GITHUB_OUTPUT"
          echo "proxmox_version=${{ env.PROXMOX_VERSION }}" >> "$GITHUB_OUTPUT"
          
      - name: Setup Docker Container
        run: |
          DISTRO="${{ steps.prepare.outputs.distro }}"
          PROXMOX_VERSION="${{ steps.prepare.outputs.proxmox_version }}"
          docker_tag="proxmox-dump-schema:${PROXMOX_VERSION}"
          schema_file="proxmox-api-schema-${PROXMOX_VERSION}.json"

          echo "Building container for distro=$DISTRO and version=$PROXMOX_VERSION"


          sudo chmod +x dump-schema/dump-schema.pl
          # Build Docker image
          docker build --platform=linux/amd64 \
            --tag "proxmox-api" \
            --build-arg DISTRO="${DISTRO}" \
            --build-arg PROXMOX_VERSION="${PROXMOX_VERSION}" \
            "./dump-schema"

      - name: Run container and extract API
        id: extract_api
        run: |
          DISTRO="${{ steps.prepare.outputs.distro }}"
          PROXMOX_VERSION="${{ steps.prepare.outputs.proxmox_version }}"

          echo "Running container and dumping API schema"

          # Run the container, executing the Perl script inside
          docker run --rm proxmox-api \
            perl /app/dump-schema.pl > "proxmox-ve-api-${PROXMOX_VERSION}.json"

          echo "Generated proxmox-ve-api-${PROXMOX_VERSION}.json"

          echo ""

          echo "$(cat "proxmox-ve-api-${PROXMOX_VERSION}.json")"

      - name: Commit and push JSON file
        run: |
          PROXMOX_VERSION="${{ steps.prepare.outputs.proxmox_version }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Commit the new JSON file
          git add "proxmox-ve-api-${PROXMOX_VERSION}.json"
          git commit -m "Add proxmox-ve-api-${PROXMOX_VERSION}.json" || echo "Nothing to commit"

          # Create a new tag
          git tag "${PROXMOX_VERSION}"

          # Push commit and tag
          git push origin HEAD
          git push origin "${PROXMOX_VERSION}"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.prepare.outputs.proxmox_version }}
          name: "Proxmox VE API Schema ${{ steps.prepare.outputs.proxmox_version }}"
          body: "Includes proxmox-ve-api-${{ steps.prepare.outputs.proxmox_version }}.json"
          draft: false
          prerelease: false
          files: Release.txt

